// 仿站-菜谱/src/views/Center/ui/ShowLoginBtn.jsx
import React, { Component } from 'react';
import store from '@/store'
import { Link } from 'react-router-dom';

class ShowLoginBtn extends Component {
  render() {
    let nickname = store.getState().getIn(['user', 'nickname']) || ''
    return (
      <>
        {
          nickname ?
            <span>{nickname}</span>
            :
            <Link to="/login">立即登录</Link>
        }
      </>
    );
  }
}

export default ShowLoginBtn;

// 仿站-卖座网/src/views/center/ui/showLoginBtn.vue
<template>
  <div>
    <router-link v-if="!isLogin" to="/login">立即登录</router-link>
    <span v-else>{{ nickname }}</span>
  </div>
</template>

<script>
import { createNamespacedHelpers } from 'vuex'
const { mapState } = createNamespacedHelpers('center')
export default {
  computed: {
    ...mapState(['token', 'nickname']),
    isLogin() {
      return this.token ? true : false
    }
  }
}
</script>

<style lang="scss" scoped></style>
